const fs = require('fs');

const enFile = '/Users/mac/.gemini/antigravity/playground/eatery-page-builder/apps/web/src/i18n/dictionaries/en.json';
const viFile = '/Users/mac/.gemini/antigravity/playground/eatery-page-builder/apps/web/src/i18n/dictionaries/vi.json';

const enData = JSON.parse(fs.readFileSync(enFile, 'utf8'));
const viData = JSON.parse(fs.readFileSync(viFile, 'utf8'));

enData.textImageBlock = {
  "layout": "Layout",
  "imgLeft": "Image Left",
  "imgRight": "Image Right",
  "stacked": "Stacked",
  "textOnly": "Text Only",
  "imgOnly": "Image Only",
  "aspectRatio": "Aspect ratio",
  "square": "Square (1:1)",
  "4_3": "4:3",
  "16_9": "16:9",
  "free": "Free",
  "padding": "Padding",
  "compact": "Compact",
  "normal": "Normal",
  "spacious": "Spacious",
  "background": "Background",
  "transparent": "Transparent",
  "solidColour": "Solid colour",
  "gradient": "Subtle gradient",
  "image": "Image",
  "clickToUpload": "Click to upload",
  "imageFit": "Image fit",
  "cover": "Cover",
  "contain": "Contain",
  "content": "Content",
  "headingOptional": "Heading (optional)",
  "headingPlaceholder": "Section title…",
  "bodyText": "Body text",
  "bodyPlaceholder": "Write your content here…\nLine breaks are preserved.",
  "textContentPlaceholder": "Text content…",
  "ctaButton": "CTA Button",
  "addCta": "+ Add CTA button",
  "styling": "Styling",
  "imageRoundness": "Image roundness",
  "none": "None",
  "small": "Small",
  "medium": "Medium",
  "large": "Large",
  "xlarge": "X-Large",
  "pill": "Pill",
  "gradientHelp": "Gradient goes top-left → bottom-right"
};

viData.textImageBlock = {
  "layout": "Bố cục",
  "imgLeft": "Ảnh bên trái",
  "imgRight": "Ảnh bên phải",
  "stacked": "Xếp chồng",
  "textOnly": "Chỉ văn bản",
  "imgOnly": "Chỉ ảnh",
  "aspectRatio": "Tỷ lệ ảnh",
  "square": "Vuông (1:1)",
  "4_3": "4:3",
  "16_9": "16:9",
  "free": "Tự do",
  "padding": "Khoảng đệm",
  "compact": "Nhỏ",
  "normal": "Bình thường",
  "spacious": "Rộng",
  "background": "Nền",
  "transparent": "Trong suốt",
  "solidColour": "Màu đơn sắc",
  "gradient": "Chuyển sắc nhẹ",
  "image": "Ảnh",
  "clickToUpload": "Nhấn để tải lên",
  "imageFit": "Hiển thị ảnh",
  "cover": "Phủ kín",
  "contain": "Thu gọn",
  "content": "Nội dung",
  "headingOptional": "Tiêu đề (tùy chọn)",
  "headingPlaceholder": "Tiêu đề phần…",
  "bodyText": "Nội dung văn bản",
  "bodyPlaceholder": "Viết nội dung của bạn ở đây…\nGiữ nguyên dấu ngắt dòng.",
  "textContentPlaceholder": "Nội dung văn bản…",
  "ctaButton": "Nút hành động",
  "addCta": "+ Thêm nút hành động",
  "styling": "Định dạng",
  "imageRoundness": "Bo góc ảnh",
  "none": "Không",
  "small": "Nhỏ",
  "medium": "Trung bình",
  "large": "Lớn",
  "xlarge": "Rất lớn",
  "pill": "Tròn trịa",
  "gradientHelp": "Màu chuyển từ trên-trái → dưới-phải"
};

enData.contactBlock = {
  "layout": "Layout",
  "stacked": "Stacked",
  "mapLeft": "Map Left",
  "appearance": "Appearance",
  "background": "Background",
  "textColour": "Text colour",
  "light": "Light",
  "dark": "Dark",
  "map": "Map",
  "showMap": "Show map",
  "mapHeight": "Map height",
  "small": "Small",
  "medium": "Medium",
  "large": "Large",
  "noAddressSet": "No address set in business profile — map will not display.",
  "contactInfo": "Contact info",
  "phoneNumber": "Phone number",
  "noPhoneSet": "No phone in business profile.",
  "emailAddress": "Email address",
  "noEmailSet": "No email in business profile.",
  "physicalAddress": "Physical address",
  "openingHours": "Opening hours",
  "socialIcons": "Social Icons",
  "noSocialsSet": "No social links set on the business profile yet. Add them in the Business settings.",
  "socialsPreview": "Socials:"
};

viData.contactBlock = {
  "layout": "Bố cục",
  "stacked": "Xếp chồng",
  "mapLeft": "Bản đồ bên trái",
  "appearance": "Giao diện",
  "background": "Nền",
  "textColour": "Màu chữ",
  "light": "Sáng",
  "dark": "Tối",
  "map": "Bản đồ",
  "showMap": "Hiện bản đồ",
  "mapHeight": "Chiều cao bản đồ",
  "small": "Nhỏ",
  "medium": "Trung bình",
  "large": "Lớn",
  "noAddressSet": "Chưa có địa chỉ trong hồ sơ doanh nghiệp — bản đồ sẽ không hiển thị.",
  "contactInfo": "Thông tin liên hệ",
  "phoneNumber": "Số điện thoại",
  "noPhoneSet": "Chưa có số điện thoại trong hồ sơ.",
  "emailAddress": "Địa chỉ Email",
  "noEmailSet": "Chưa có email trong hồ sơ.",
  "physicalAddress": "Địa chỉ thực tế",
  "openingHours": "Giờ mở cửa",
  "socialIcons": "Biểu tượng MXH",
  "noSocialsSet": "Chưa có liên kết mạng xã hội trong hồ sơ doanh nghiệp. Thêm chúng trong phần Cài đặt doanh nghiệp.",
  "socialsPreview": "Mạng xã hội:"
};

enData.menuGridBlock = {
  "layout": "Layout",
  "col2": "2 Col",
  "col3": "3 Col",
  "col4": "4 Col",
  "list": "List",
  "sectionHeading": "Section heading",
  "headingPlaceholder": "Our Menu",
  "headingHelp": "Optional title shown above the menu grid.",
  "description": "Description",
  "descPlaceholder": "A short description about this menu section...",
  "selectionMode": "Selection Mode",
  "byCategory": "By Category",
  "customItems": "Custom Items",
  "categoriesToShow": "Categories to show",
  "noCategories": "No menu categories yet. Add them in the Menu builder first.",
  "allCategories": "All categories",
  "hidden": "(hidden)",
  "itemsToShow": "Items to show",
  "noItems": "No menu items yet. Add them in the Menu builder first.",
  "soldOut": "(sold out)",
  "displayOptions": "Display options",
  "categoryFilterTabs": "Category filter tabs",
  "autoCats": "Auto (2+ cats)",
  "itemImages": "Item images",
  "itemDescriptions": "Item descriptions",
  "prices": "Prices",
  "soldOutBadge": "\"Sold Out\" badge",
  "colours": "Colours",
  "background": "Background",
  "text": "Text",
  "tabsOn": "Tabs on",
  "noTabs": "No tabs",
  "menu": "Menu"
};

viData.menuGridBlock = {
  "layout": "Bố cục",
  "col2": "2 Cột",
  "col3": "3 Cột",
  "col4": "4 Cột",
  "list": "Danh sách",
  "sectionHeading": "Tiêu đề phần",
  "headingPlaceholder": "Thực đơn của chúng tôi",
  "headingHelp": "Tiêu đề tùy chọn hiển thị phía trên thực đơn.",
  "description": "Mô tả",
  "descPlaceholder": "Mô tả ngắn về phần thực đơn này...",
  "selectionMode": "Chế độ chọn",
  "byCategory": "Theo danh mục",
  "customItems": "Các món tùy chọn",
  "categoriesToShow": "Danh mục hiển thị",
  "noCategories": "Chưa có danh mục thực đơn. Hãy thêm trong trình tạo Thực đơn trước.",
  "allCategories": "Tất cả danh mục",
  "hidden": "(đã ẩn)",
  "itemsToShow": "Các món hiển thị",
  "noItems": "Chưa có món ăn nào. Hãy thêm trong trình tạo Thực đơn trước.",
  "soldOut": "(hết hàng)",
  "displayOptions": "Tùy chọn hiển thị",
  "categoryFilterTabs": "Thẻ lọc danh mục",
  "autoCats": "Tự động (2+ danh mục)",
  "itemImages": "Ảnh món ăn",
  "itemDescriptions": "Mô tả món ăn",
  "prices": "Giá",
  "soldOutBadge": "Nhãn \"Hết hàng\"",
  "colours": "Màu sắc",
  "background": "Nền",
  "text": "Chữ",
  "tabsOn": "Bật thẻ lọc",
  "noTabs": "Tắt thẻ lọc",
  "menu": "Thực đơn"
};

fs.writeFileSync(enFile, JSON.stringify(enData, null, 2) + '\n');
fs.writeFileSync(viFile, JSON.stringify(viData, null, 2) + '\n');
console.log('Dictionaries updated!');
